"""empty message

Revision ID: 385dade41242
Revises: e54a1ae82941
Create Date: 2019-06-19 23:01:08.696540

"""

# revision identifiers, used by Alembic.
revision = '385dade41242'
down_revision = 'e54a1ae82941'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
