"""empty message

Revision ID: e54a1ae82941
Revises: 4f2e2c180af
Create Date: 2019-06-18 15:29:56.574418

"""

# revision identifiers, used by Alembic.
revision = 'e54a1ae82941'
down_revision = '4f2e2c180af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('producer', sa.String(length=300), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('actor1', sa.String(length=300), nullable=True),
    sa.Column('actor2', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('title')
    )
    op.create_table('user',
    sa.Column('user_name', sa.String(length=300), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_name')
    )
    op.create_table('notation',
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('movie_title', sa.String(length=300), nullable=False),
    sa.Column('username', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['movie_title'], ['movie.title'], ),
    sa.ForeignKeyConstraint(['username'], ['user.user_name'], ),
    sa.PrimaryKeyConstraint('movie_title', 'username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notation')
    op.drop_table('user')
    op.drop_table('movie')
    # ### end Alembic commands ###
