""" create the Notation table

Revision ID: f334786af046
Revises: 625abde9428c
Create Date: 2019-06-18 13:04:32.316665

"""

# revision identifiers, used by Alembic.
revision = 'f334786af046'
down_revision = '625abde9428c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
